theme: jekyll-theme-slate
title: "Rafaldini's Coding Journal"
markdown: kramdown
safe: true
url: "https://lucasrafaldini.github.io"
plugins:
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-feed
  - jekyll-avatar
  - github-pages-health-check
  - github-pages
jekyll-mentions:
  base_url: https://twitter.com
  
relative_links:
  enabled: true
  collections: true
